parameters:
#    acme_films.example.class: Acme\FilmsBundle\Example

services:
#    acme_films.example:
#        class: %acme_films.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
